### ISSUE TITLE
Working Offline

### ISSUE THREAD

**Issue by cemalgnlts** [codesandbox/nodebox-runtime#37]
Hi,

Is there any way to work completely offline once you have installed all the packages?

Can PWA cache all required files?

Thanks.

**Comment by cemalgnlts** [comment]
It says here that sandpack can work offline with cache: https://sandpack.codesandbox.io/docs/guides/hosting-the-bundler#offline-support

If sandpack uses nodebox, shouldn't it also work offline with cache.

**Comment by DeMoorJasper** [comment]
> It says here that sandpack can work offline with cache: https://sandpack.codesandbox.io/docs/guides/hosting-the-bundler#offline-support
> 
> 
> 
> If sandpack uses nodebox, shouldn't it also work offline with cache.

Currently nodebox takes a new domain for the preview every time you render it as it was the safest way to ensure consistent update logic and a single nodebox instance is connected to the preview.

Because of this we need a network connection for the initial render and once it's rendered you can remove internet for any additional changes.

We could make our caching on service workers a bit more aggressive but the core issue will remain and is really hard to fix properly without introducing more issues.

**Comment by cemalgnlts** [comment]
Understood thanks.
